### ISSUE TITLE
Improve interface for testing data

### ISSUE THREAD

**Issue by SeanPlusPlus** [klpontz/ransom-note#4]
Currently, the only way to test this function is to create 2 files, and then enter in those file name by hand when running this on the command line:

https://github.com/klpontz/ransom-note/blob/57802f1838e6d5494e77c0184f04c9bbc3ce6f59/main.py#L5-L20

Add option that accepts strings directly from the command line. 

Something, for example, that would look like this:

```
python main.py --message "Hello World" --ransom "Foo Bar"
```

... That way, we can easily test many different variant strings for both message and ransom ...

`argparse` is a helpful library for this

**Comment by klpontz** [comment]
Used argparse to read in strings from the terminal using the syntax:

python main.py --ransom 'Give me money' --magazine 'Not giving you any money.'

Here's the commit: 94c18aec88999383335f1bebaa9ccab75fb390ad

**Comment by SeanPlusPlus** [comment]
RAD!!! Works like a charm!!!
