### ISSUE TITLE
Check fails when magazine contains single character

### ISSUE THREAD

**Issue by SeanPlusPlus** [klpontz/ransom-note#7]
### Version

https://github.com/klpontz/ransom-note/tree/94c18aec88999383335f1bebaa9ccab75fb390ad

### Input

```
python main.py --ransom 'Give me money' --magazine 'x'
```

### Output

```
Welcome. Let's determine if the ransom note was created with a specific magazine.

TRUE: the ransom note may have been created with this magazine.
```

### Expected

This ransom note can not be generated from this magazine

**Comment by klpontz** [comment]
That is strange behavior! I'll take a look.

**Comment by SeanPlusPlus** [comment]
Looks good!
